### ISSUE TITLE
"pretrained_linear_transform" in /config/flow_deformation.yml

### ISSUE THREAD

**Issue by shijinjin12** [ArjunNarayanan/LinFlo-Net#4] opened 2024-05-24 02:50 UTC
when I change "/config/flow_deformation.yml" to run the command,
"python workflows/train_flow_with_udf.py -config /path/to/config/file”, I don't know what the path that should be filled in "pretrained_linear_transform" in the "flow_deformation.yml" file. I can't find the "pretrained folder".

**Comment by ArjunNarayanan** [comment] 2024-05-28 14:52
Duplicate of #3 -- closing this issue and discussing there.

**Closed as completed by ArjunNarayanan** 2024-05-28 14:52 UTC
